### ISSUE TITLE
genode_tz_io undefined

### ISSUE THREAD

**Issue by ykram** [m-stein/linux#1]
Built the latest repo version with the genode toolchain and all seemed good except the following errors provided at the bottom:

  OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
  Building modules, stage 2.
  MODPOST 256 modules
ERROR: "genode_tz_io" [drivers/usb/host/ehci-hcd.ko] undefined!
ERROR: "genode_tz_io" [drivers/usb/chipidea/usbmisc_imx.ko] undefined!
ERROR: "genode_tz_io" [drivers/usb/chipidea/ci_hdrc_msm.ko] undefined!
ERROR: "genode_tz_io" [drivers/usb/chipidea/ci_hdrc.ko] undefined!
make[1]: **\* [__modpost] Error 1
make: **\* [modules] Error 2

**Comment by m-stein** [comment]
I assume that you've used the `usb_armory_genode_tz_vmm` branch. Please correct me if I'm wrong. I've not tested building linux with the genode toolchain. I use the following procedure:

```
### Get toolchain ###
wget http://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-none-eabi-4.9-2014.09_linux.tar.xz
tar xvf gcc-linaro-arm-none-eabi-4.9-2014.09_linux.tar.xz -C $MY_GCC_DIR

### Build ###
make -C $MY_LX_SRC_DIR   ARCH=arm CROSS_COMPILE=$MY_GCC_DIR/bin/arm-none-eabi- O=$MY_LX_BUILD_DIR imx_v53_usb_armory_defconfig &&
make -C $MY_LX_BUILD_DIR ARCH=arm CROSS_COMPILE=$MY_GCC_DIR/bin/arm-none-eabi- -j$MY_CPUS zImage LOADADDR=0x80008000 &&
make -C $MY_LX_BUILD_DIR ARCH=arm CROSS_COMPILE=$MY_GCC_DIR/bin/arm-none-eabi- dtbs
```

With this workflow, I wasn't able to reproduce your problem. Does it still occur if you follow my suggestions?

**Comment by ykram** [comment]
Yup, that fixed it. I wasn't aware I had to use a different toolchain and was under the impression the genode toolchain was needed. Thanks for letting me know :)

**Comment by m-stein** [comment]
Glad that I could help you :)
